#!/usr/bin/env bash
# Show all attached IPs
# ifconfig | grep "inet addr" | awk '{print $2}' | cut -d":" -f2
# Using experimental -P option of grep
ifconfig | grep -Eo "inet (addr:)?([0-9]*\.){3}[0-9]*" | cut -b 11-
